openapi: 3.0.0
info:
  title: Data
  version: '1.0'
servers:
  - url: 'https://st-api.gleads.io'
    description: DEV API
paths:
  /api/private/data/countries:
    get:
      summary: Get countries list
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  critical:
                    type: boolean
                  countries:
                    type: object
                    properties:
                      AF:
                        type: object
                        properties:
                          iso:
                            type: string
                            minLength: 1
                          name:
                            type: string
                            minLength: 1
                        required:
                          - iso
                          - name
                      AL:
                        type: object
                        properties:
                          iso:
                            type: string
                            minLength: 1
                          name:
                            type: string
                            minLength: 1
                        required:
                          - iso
                          - name
                      DZ:
                        type: object
                        properties:
                          iso:
                            type: string
                            minLength: 1
                          name:
                            type: string
                            minLength: 1
                        required:
                          - iso
                          - name
                    required:
                      - AF
                      - AL
                      - DZ
                required:
                  - code
                  - critical
                  - countries
              examples:
                Countries list:
                  value:
                    code: 1000
                    critical: true
                    countries:
                      AF:
                        iso: AF
                        name: Afghanistan
                      AL:
                        iso: AL
                        name: Albania
                      DZ:
                        iso: DZ
                        name: Algeria
                      AS:
                        iso: AS
                        name: American Samoa
                      AD:
                        iso: AD
                        name: Andorra
                      AO:
                        iso: AO
                        name: Angola
                      AI:
                        iso: AI
                        name: Anguilla
                      AQ:
                        iso: AQ
                        name: Antarctica
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  name:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                  code:
                    type: number
                  type:
                    type: string
                    minLength: 1
                required:
                  - name
                  - message
                  - code
                  - type
              examples:
                Invalid token:
                  value:
                    name: UnAuthorizedError
                    message: Unauthorized
                    code: 401
                    type: INVALID_TOKEN
                No token provided:
                  value:
                    name: UnAuthorizedError
                    message: Unauthorized
                    code: 401
                    type: NO_TOKEN
      operationId: get-api-private-data-countries
      description: Get countries list
      security:
        - Session token: []
components:
  schemas: {}
  securitySchemes:
    Session token:
      type: http
      scheme: bearer
